### PR TITLE
[#175740454] Align with BPD definitive views

### PR DESCRIPTION
**Pull request by BurnedMarshal**
Upgrade models with BPD definitive view specification.

### CODE REVIEW

**Review by AleDore — APPROVED** [review]
lgtm

**Review by pasqualedevita — COMMENTED** [review]
setting Iban type it could be a problem if there was a dirty or unexpected data.

https://github.com/pagopa/io-functions-backoffice/blob/175740454-upgrade-models-views/models/citizen.ts#L27

We are working in readonly mode so we can take values as is without any checks.

**Comment by BurnedMarshal** [comment]
> setting Iban and FiscalCode type it could be a problem if there was a dirty or unexpected data.
> 
> https://github.com/pagopa/io-functions-backoffice/blob/175740454-upgrade-models-views/models/citizen.ts#L22
> https://github.com/pagopa/io-functions-backoffice/blob/175740454-upgrade-models-views/models/citizen.ts#L27
> 
> We are working in readonly mode so we can take values as is without any checks.

@pasqualedevita this kind of problems can happen only on severe software malfunction or data corruption. Anyway, the response validation failures return a `ResponseErrorValidation` that could be manifest to the back-office user that data corruption is under the way for that citizen.

**Comment by BurnedMarshal** [comment]
@pasqualedevita removed IBAN validation and type in 32aba03

**Pull request merged**
